apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
        tier: database
    spec:
      containers:
        - name: db
          image: mysql:8.0.11
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
              name: db
          envFrom:
            - secretRef:
                name: server-secret
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
            subPath: mysql
          - name: mysql-config-volume
            mountPath: /etc/mysql/conf.d/default_auth.cnf
            subPath: default_auth
      volumes:
          - name: mysql-persistent-storage
            persistentVolumeClaim:
              claimName: mysql-pv-claim
          - name: mysql-config-volume
            configMap:
              name: mysql-config




              #        volumes:
              #
