apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-pv-claim
  labels:
    app: ipfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 20Gi
